// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chsufgnoqzxcrcnwflph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoc3VmZ25vcXp4Y3JjbndmbHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzk1MjksImV4cCI6MjA2NzYxNTUyOX0.KuTL03Y-SoK09tYO6ZQibtpURQ7vEV9KVtgqppX3x5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});